=== Riverscapes/QRiS/resources/protocol.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Define the Metadata group -->
    <xs:group name="MetadataGroup">
        <xs:sequence>
            <xs:element name="Metadata" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="MetadataItem" minOccurs="1" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="Name" type="xs:string" minOccurs="1" maxOccurs="1"/>
                                    <xs:element name="Value" type="xs:string" minOccurs="1" maxOccurs="1"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:group>

    <xs:element name="Protocol">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Label" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="Description" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="URL" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="Citation" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="Author" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="CreationDate" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="UpdatedDate" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:group ref="MetadataGroup"/>
                <xs:element name="Layers">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Layer" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Label" type="xs:string" minOccurs="1" maxOccurs="1"/>
                                        <xs:element name="Symbology" type="xs:string" minOccurs="1" maxOccurs="1"/>
                                        <xs:element name="Description" type="xs:string" minOccurs="0" maxOccurs="1"/>
                                        <xs:element name="MenuItems" minOccurs="0" maxOccurs="1">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="MenuItem" minOccurs="1" maxOccurs="unbounded"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Hierarchy" minOccurs="0" maxOccurs="1">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="HierarchyItem" minOccurs="1" maxOccurs="unbounded"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Fields" minOccurs="0" maxOccurs="1">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Field" minOccurs="1" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="Label" type="xs:string" minOccurs="1" maxOccurs="1"/>
                                                                <xs:element name="DefaultValue" type="xs:string" minOccurs="0" maxOccurs="1"/>
                                                                <xs:element name="LookupValues" minOccurs="0" maxOccurs="1">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="LookupValue" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                                                                        </xs:sequence>
                                                                        <xs:attribute name="allow_custom_values" type="xs:boolean" default="false" use="optional"/>
                                                                    </xs:complexType>        
                                                                </xs:element>
                                                            </xs:sequence>
                                                            <xs:attribute name="machine_code" type="xs:string" use="required"/>
                                                            <xs:attribute name="version" type="xs:string" use="required"/>
                                                            <xs:attribute name="type" use="required">
                                                                <xs:simpleType>
                                                                    <xs:restriction base="xs:string">
                                                                        <xs:enumeration value="text"/>
                                                                        <xs:enumeration value="float"/>
                                                                        <xs:enumeration value="integer"/>
                                                                        <xs:enumeration value="list"/>
                                                                        <xs:enumeration value="attachment"/>
                                                                    </xs:restriction>
                                                                </xs:simpleType>
                                                            </xs:attribute>
                                                            <xs:attribute name="value_required" type="xs:boolean" default="false" use="optional"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:group ref="MetadataGroup"/>
                                    </xs:sequence>
                                    <xs:attribute name="machine_code" type="xs:string" use="required"/>
                                    <xs:attribute name="version" type="xs:string" use="required"/>
                                    <xs:attribute name="geom_type" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="Point"/>
                                                <xs:enumeration value="Linestring"/>
                                                <xs:enumeration value="Polygon"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Metrics" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Metric" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Label" type="xs:string" minOccurs="1" maxOccurs="1"/>
                                        <xs:element name="DefaultLevel" minOccurs="1" maxOccurs="1">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="Metric"/>
                                                    <xs:enumeration value="Indicator"/>
                                                    <xs:enumeration value="None"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="Description" type="xs:string" minOccurs="0" maxOccurs="1"/>
                                        <xs:element name="DefinitionURL" type="xs:string" minOccurs="0" maxOccurs="1"/>
                                        <xs:element name="MinimumValue" type="xs:float" minOccurs="0" maxOccurs="1"/>
                                        <xs:element name="MaximumValue" type="xs:float" minOccurs="0" maxOccurs="1"/>
                                        <xs:element name="Precision" type="xs:integer" minOccurs="0" maxOccurs="1"/>
                                        <xs:element name="Parameters">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Inputs" minOccurs="0" maxOccurs="1">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="Input" minOccurs="1" maxOccurs="unbounded">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="Usage" minOccurs="0" maxOccurs="1">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string">
                                                                                        <xs:enumeration value="Normalization"/>
                                                                                        <xs:enumeration value="Surface"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                        <xs:attribute name="machine_code_reference" use="required">
                                                                            <xs:simpleType>
                                                                                <xs:restriction base="xs:string">
                                                                                    <xs:enumeration value="dem"/> 
                                                                                    <xs:enumeration value="centerline"/>
                                                                                    <xs:enumeration value="surface"/>
                                                                                    <xs:enumeration value="valley_bottom"/>
                                                                                </xs:restriction>
                                                                            </xs:simpleType>
                                                                        </xs:attribute>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="DCELayers" minOccurs="0" maxOccurs="1">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="DCELayer" minOccurs="1" maxOccurs="unbounded">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="Usage" minOccurs="0" maxOccurs="1">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string">
                                                                                        <xs:enumeration value="Denominator"/>
                                                                                        <xs:enumeration value="Numerator"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element name="CountField" type="xs:string" minOccurs="0" maxOccurs="1"/>
                                                                            <xs:element name="AttributeFilter" minOccurs="0" maxOccurs="1">
                                                                                <xs:complexType>
                                                                                    <xs:sequence>
                                                                                        <xs:element name="Value" minOccurs="1" maxOccurs="unbounded"/>
                                                                                    </xs:sequence>
                                                                                    <xs:attribute name="field" type="xs:string" use="required"/>
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                        <xs:attribute name="machine_code_reference" use="required"/>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>                                         
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="machine_code" type="xs:string" use="required"/>
                                    <xs:attribute name="version" type="xs:string" use="required"/>
                                    <xs:attribute name="calculation_machine_code" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>

                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="machine_code" type="xs:string" use="required"/>
            <xs:attribute name="version" type="xs:string" use="required"/>
            <xs:attribute name="status" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="experimental"/>
                        <xs:enumeration value="production"/>
                        <xs:enumeration value="deprecated"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Riverscapes/QRiS/resources/protocols/test.xml
<Protocol machine_code="TEST_PROTOCOL" version="1.0" status="production" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://xml.riverscapes.net/QRiS/protocol.xsd">
    <Label>Example Protocol</Label>
    <Description>Example Description</Description>
    <URL>http://example.com</URL>
    <Citation>Example Citation</Citation>
    <Author>Author Name</Author>
    <CreationDate>2023-01-01</CreationDate>
    <UpdatedDate>2023-01-02</UpdatedDate>
    <MetaData>
        <Meta name="Example Metadata">Example Value</Meta>
        <Meta name="Example2">Example value 3</Meta>
    </MetaData>
    <Layers>
        <Layer id="layer1" version="1.0" geom_type="Point">
            <Label>Layer 1</Label>
            <Symbology>Symbology 1</Symbology>
            <Description>Layer 1 Description</Description>
            <Fields>
                <IntegerField id="count_field" version="1.0">
                    <Label>Count Field</Label>
                </IntegerField>
                <TextField id="type_field" version="1.0">
                    <Label>Type Field</Label>
                </TextField>
            </Fields>
        </Layer>
        <Layer id="layer2" version="1.0" geom_type="Polygon">
            <Label>Layer 2</Label>
            <Symbology>Symbology 2</Symbology>
            <Description>Layer 2 Description</Description>
            <Fields>
                <TextField id="type_field" version="1.0">
                    <Label>Type Field</Label>
                </TextField>
            </Fields>
        </Layer>
        <Layer id="layer3" version="1.0" geom_type="Linestring">
            <Label>Layer 3</Label>
            <Symbology>Symbology 3</Symbology>
            <Description>Layer 3 Description</Description>
            <Fields>
                <ListField id="list_field" version="1.0">
                    <Label>List Field</Label>
                    <Values allow_multiple_values="true">
                        <Value>Value 1</Value>
                        <Value>Value 2</Value>
                    </Values>
                </ListField>
                <TextField id="text_field" version="1.0">
                    <Label>Text Field</Label>
                    <Visibility field_id_ref="list_field">
                        <Values>
                            <Value>Value 1</Value>
                        </Values>
                    </Visibility>
                </TextField>
            </Fields>
        </Layer>
        <Layer id="layer4" version="1.0" geom_type="Point">
            <Label>Layer 4 (Slider)</Label>
            <Symbology>Symbology 4</Symbology>
            <Description>Layer 4 Description</Description>
            <Fields>
                <IntegerField id="count_field" version="1.0">
                    <Label>Count Field</Label>
                    <Slider min="0" max="100" step="1"/>
                </IntegerField>
                <TextField id="type_field" version="1.0">
                    <Label>Type Field</Label>
                </TextField>
            </Fields>
        </Layer>
    </Layers>
    <Metrics>
        <Metric id="metric1" version="1.0" calculation_machine_code="count">
            <Label>Metric 1</Label>
            <DefaultLevel>Metric</DefaultLevel>
            <Description>Metric 1 Description</Description>
            <DefinitionURL>http://example.com/metric1</DefinitionURL>
            <MinimumValue>0</MinimumValue>
            <Precision>1</Precision>
            <Parameters>
                <DCELayer layer_id_ref="layer1">
                    <Usage>Denominator</Usage>
                    <CountField field_id_ref="count_field"/>
                    <AttributeFilter field_id_ref="type_Field">
                        <Value>Type 1</Value>
                    </AttributeFilter>
                </DCELayer>
            </Parameters>
        </Metric>
        <Metric id="metric2" version="1.0" calculation_machine_code="count">
            <Label>Metric 2</Label>
            <DefaultLevel>Metric</DefaultLevel>
            <Description>Metric 2 Description</Description>
            <DefinitionURL>http://example.com/metric2</DefinitionURL>
            <MinimumValue>0</MinimumValue>
            <Precision>2</Precision>
            <Parameters>
            <!-- This layer_id_ref should be red -->
                <DCELayer layer_id_ref="layer2_id_does_not_exist">
                    <Usage>Numerator</Usage>
                    <AttributeFilter field_id_ref="type_field">
                        <Value>Type 2</Value>
                    </AttributeFilter>
                </DCELayer>
            </Parameters>
        </Metric>
    </Metrics>
</Protocol>
