=== Riverscapes/QRiS/resources/protocol.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Define the Metadata group -->
    <xs:group name="MetadataGroup">
        <xs:sequence>
            <xs:element name="Metadata" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="MetadataItem" minOccurs="1" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="Name" type="xs:string" minOccurs="1" maxOccurs="1"/>
                                    <xs:element name="Value" type="xs:string" minOccurs="1" maxOccurs="1"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:group>

    <xs:element name="Protocol">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Label" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="Description" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="URL" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="Citation" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="Author" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="CreationDate" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="UpdatedDate" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:group ref="MetadataGroup"/>
                <xs:element name="Layers">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Layer" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Label" type="xs:string" minOccurs="1" maxOccurs="1"/>
                                        <xs:element name="Symbology" type="xs:string" minOccurs="1" maxOccurs="1"/>
                                        <xs:element name="Description" type="xs:string" minOccurs="0" maxOccurs="1"/>
                                        <xs:element name="MenuItems" minOccurs="0" maxOccurs="1">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="MenuItem" minOccurs="1" maxOccurs="unbounded"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Hierarchy" minOccurs="0" maxOccurs="1">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="HierarchyItem" minOccurs="1" maxOccurs="unbounded"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Fields" minOccurs="0" maxOccurs="1">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Field" minOccurs="1" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="Label" type="xs:string" minOccurs="1" maxOccurs="1"/>
                                                                <xs:element name="DefaultValue" type="xs:string" minOccurs="0" maxOccurs="1"/>
                                                                <xs:element name="LookupValues" minOccurs="0" maxOccurs="1">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="LookupValue" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                                                                        </xs:sequence>
                                                                        <xs:attribute name="allow_custom_values" type="xs:boolean" default="false" use="optional"/>
                                                                    </xs:complexType>        
                                                                </xs:element>
                                                            </xs:sequence>
                                                            <xs:attribute name="machine_code" type="xs:string" use="required"/>
                                                            <xs:attribute name="version" type="xs:string" use="required"/>
                                                            <xs:attribute name="type" use="required">
                                                                <xs:simpleType>
                                                                    <xs:restriction base="xs:string">
                                                                        <xs:enumeration value="text"/>
                                                                        <xs:enumeration value="float"/>
                                                                        <xs:enumeration value="integer"/>
                                                                        <xs:enumeration value="list"/>
                                                                        <xs:enumeration value="attachment"/>
                                                                    </xs:restriction>
                                                                </xs:simpleType>
                                                            </xs:attribute>
                                                            <xs:attribute name="value_required" type="xs:boolean" default="false" use="optional"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:group ref="MetadataGroup"/>
                                    </xs:sequence>
                                    <xs:attribute name="machine_code" type="xs:string" use="required"/>
                                    <xs:attribute name="version" type="xs:string" use="required"/>
                                    <xs:attribute name="geom_type" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="Point"/>
                                                <xs:enumeration value="Linestring"/>
                                                <xs:enumeration value="Polygon"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Metrics" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Metric" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Label" type="xs:string" minOccurs="1" maxOccurs="1"/>
                                        <xs:element name="DefaultLevel" minOccurs="1" maxOccurs="1">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="Metric"/>
                                                    <xs:enumeration value="Indicator"/>
                                                    <xs:enumeration value="None"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="Description" type="xs:string" minOccurs="0" maxOccurs="1"/>
                                        <xs:element name="DefinitionURL" type="xs:string" minOccurs="0" maxOccurs="1"/>
                                        <xs:element name="MinimumValue" type="xs:float" minOccurs="0" maxOccurs="1"/>
                                        <xs:element name="MaximumValue" type="xs:float" minOccurs="0" maxOccurs="1"/>
                                        <xs:element name="Precision" type="xs:integer" minOccurs="0" maxOccurs="1"/>
                                        <xs:element name="Parameters">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Inputs" minOccurs="0" maxOccurs="1">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="Input" minOccurs="1" maxOccurs="unbounded">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="Usage" minOccurs="0" maxOccurs="1">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string">
                                                                                        <xs:enumeration value="Normalization"/>
                                                                                        <xs:enumeration value="Surface"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                        <xs:attribute name="machine_code_reference" use="required">
                                                                            <xs:simpleType>
                                                                                <xs:restriction base="xs:string">
                                                                                    <xs:enumeration value="dem"/> 
                                                                                    <xs:enumeration value="centerline"/>
                                                                                    <xs:enumeration value="surface"/>
                                                                                    <xs:enumeration value="valley_bottom"/>
                                                                                </xs:restriction>
                                                                            </xs:simpleType>
                                                                        </xs:attribute>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="DCELayers" minOccurs="0" maxOccurs="1">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="DCELayer" minOccurs="1" maxOccurs="unbounded">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="Usage" minOccurs="0" maxOccurs="1">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string">
                                                                                        <xs:enumeration value="Denominator"/>
                                                                                        <xs:enumeration value="Numerator"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element name="CountField" type="xs:string" minOccurs="0" maxOccurs="1"/>
                                                                            <xs:element name="AttributeFilter" minOccurs="0" maxOccurs="1">
                                                                                <xs:complexType>
                                                                                    <xs:sequence>
                                                                                        <xs:element name="Value" minOccurs="1" maxOccurs="unbounded"/>
                                                                                    </xs:sequence>
                                                                                    <xs:attribute name="field" type="xs:string" use="required"/>
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                        <xs:attribute name="machine_code_reference" use="required"/>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>                                         
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="machine_code" type="xs:string" use="required"/>
                                    <xs:attribute name="version" type="xs:string" use="required"/>
                                    <xs:attribute name="calculation_machine_code" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>

                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="machine_code" type="xs:string" use="required"/>
            <xs:attribute name="version" type="xs:string" use="required"/>
            <xs:attribute name="status" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="experimental"/>
                        <xs:enumeration value="production"/>
                        <xs:enumeration value="deprecated"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Riverscapes/QRiS/resources/as_built_protocol.xml
<Protocol machine_code="AS_BUILT" version="1.0" status="experimental" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="protocol.xsd">
    <Label>As-Built Protocol</Label>
    <Description>As-Built Layers</Description>
    <URL>https://lowtechpbr.restoration.usu.edu/</URL>
    <Citation> Wheaton J.M., Bennett S.N., Bouwes, N., Maestas J.D. and Shahverdian S.M. (Editors). 2019. Low-Tech Process-Based Restoration of Riverscapes: Design Manual. Version 1.0. Utah State University Restoration Consortium. Logan, UT. 286 pp. DOI: 10.13140/RG.2.2.19590.63049/2.</Citation>
    <Author>Nick Weber</Author>
    <CreationDate>2024-09-01</CreationDate>
    <UpdatedDate>2024-09-01</UpdatedDate>
    <Metadata>
        <MetadataItem>
            <Name>My Meta</Name>
            <Value>Data</Value>
        </MetadataItem>
    </Metadata>
    <Layers>
        <Layer id="structure_points" version="1.0" geom_type="Point">
            <Label>Structure Points</Label>
            <Symbology>structure_points.qml</Symbology>
            <Description>Structure Points Layer</Description>
            <Hierarchy>
                <HierarchyItem>Structures</HierarchyItem>
            </Hierarchy>
            <Fields>
                <Field id="structure_type" version="1.0" type="list">
                    <Label>Structure Type</Label>
                    <LookupValues>
                        <LookupValue>ALS</LookupValue>
                        <LookupValue>ALS - Bank Attached</LookupValue>
                        <LookupValue>ALS - Bank Blaster</LookupValue>
                        <LookupValue>ALS - Channel Spanning</LookupValue>
                        <LookupValue>ALS - Rhino</LookupValue>
                        <LookupValue>BDA</LookupValue>
                        <LookupValue>BDA Postless</LookupValue>
                        <LookupValue>Bag Plugs</LookupValue>
                        <LookupValue>Fell Tree</LookupValue>
                        <LookupValue>Floodplain BDA</LookupValue>
                        <LookupValue>Floodplain LWD</LookupValue>
                        <LookupValue>Full Tree</LookupValue>
                        <LookupValue>Grip Hoist Tree</LookupValue>
                        <LookupValue>Headcut Treatment</LookupValue>
                        <LookupValue>Leaky Dam</LookupValue>
                        <LookupValue>One Rock Dam</LookupValue>
                        <LookupValue>PALS</LookupValue>
                        <LookupValue>PALS - Bank Attached</LookupValue>
                        <LookupValue>PALS - Bank Blaster</LookupValue>
                        <LookupValue>PALS - Channel Spanning</LookupValue>
                        <LookupValue>PALS - Constriction Jet</LookupValue>
                        <LookupValue>PALS - Left Bank Attached</LookupValue>
                        <LookupValue>PALS - Mid Channel</LookupValue>
                        <LookupValue>PALS - Rhino</LookupValue>
                        <LookupValue>PALS - Right Bank Attached</LookupValue>
                        <LookupValue>Post and Brush Plug</LookupValue>
                        <LookupValue>Postline Wicker Weave</LookupValue>
                        <LookupValue>Primary BDA</LookupValue>
                        <LookupValue>Rhino</LookupValue>
                        <LookupValue>Secondary BDA</LookupValue>
                        <LookupValue>Sedge Plugs</LookupValue>
                        <LookupValue>Spreaders</LookupValue>
                        <LookupValue>Strategic Felling</LookupValue>
                        <LookupValue>Tight PALS (BDA without sod)</LookupValue>
                        <LookupValue>Tree Dam</LookupValue>
                        <LookupValue>Tree Plug</LookupValue>
                        <LookupValue>Vanes</LookupValue>
                        <LookupValue>Wicker Weirs</LookupValue>
                        <LookupValue>Wood Jam</LookupValue>
                        <LookupValue>Zuni Bowl</LookupValue>
                    </LookupValues>
                </Field>
            </Fields>
        </Layer>
        <Layer id="structure_lines" version="1.0" geom_type="Linestring">
            <Label>Structure Lines</Label>
            <Symbology>structure_lines.qml</Symbology>
            <Description>Structure Lines Layer</Description>
            <Hierarchy>
                <HierarchyItem>Structures</HierarchyItem>
            </Hierarchy>
            <Fields>
                <Field id="structure_type" version="1.0" type="list">
                    <Label>Structure Type</Label>
                    <LookupValues>
                        <LookupValue>ALS</LookupValue>
                        <LookupValue>ALS - Bank Attached</LookupValue>
                        <LookupValue>ALS - Bank Blaster</LookupValue>
                        <LookupValue>ALS - Channel Spanning</LookupValue>
                        <LookupValue>ALS - Rhino</LookupValue>
                        <LookupValue>BDA</LookupValue>
                        <LookupValue>BDA Postless</LookupValue>
                        <LookupValue>Bag Plugs</LookupValue>
                        <LookupValue>Fell Tree</LookupValue>
                        <LookupValue>Floodplain BDA</LookupValue>
                        <LookupValue>Floodplain LWD</LookupValue>
                        <LookupValue>Full Tree</LookupValue>
                        <LookupValue>Grip Hoist Tree</LookupValue>
                        <LookupValue>Headcut Treatment</LookupValue>
                        <LookupValue>Leaky Dam</LookupValue>
                        <LookupValue>One Rock Dam</LookupValue>
                        <LookupValue>PALS</LookupValue>
                        <LookupValue>PALS - Bank Attached</LookupValue>
                        <LookupValue>PALS - Bank Blaster</LookupValue>
                        <LookupValue>PALS - Channel Spanning</LookupValue>
                        <LookupValue>PALS - Constriction Jet</LookupValue>
                        <LookupValue>PALS - Left Bank Attached</LookupValue>
                        <LookupValue>PALS - Mid Channel</LookupValue>
                        <LookupValue>PALS - Rhino</LookupValue>
                        <LookupValue>PALS - Right Bank Attached</LookupValue>
                        <LookupValue>Post and Brush Plug</LookupValue>
                        <LookupValue>Postline Wicker Weave</LookupValue>
                        <LookupValue>Primary BDA</LookupValue>
                        <LookupValue>Rhino</LookupValue>
                        <LookupValue>Secondary BDA</LookupValue>
                        <LookupValue>Sedge Plugs</LookupValue>
                        <LookupValue>Spreaders</LookupValue>
                        <LookupValue>Strategic Felling</LookupValue>
                        <LookupValue>Tight PALS (BDA without sod)</LookupValue>
                        <LookupValue>Tree Dam</LookupValue>
                        <LookupValue>Tree Plug</LookupValue>
                        <LookupValue>Vanes</LookupValue>
                        <LookupValue>Wicker Weirs</LookupValue>
                        <LookupValue>Wood Jam</LookupValue>
                        <LookupValue>Zuni Bowl</LookupValue>
                    </LookupValues>
                </Field>
            </Fields>
        </Layer>
        <Layer id="observation_points_asbuilt" version="1.0" geom_type="Point">
            <Label>Observations</Label>
            <Symbology>observation_points_asbuilt.qml</Symbology>
            <Description>Observations Points Layer</Description>
            <Fields>
                <Field id="photo_path" version="1.0" type="attachment">
                    <Label>Photo Path</Label>
                </Field>
            </Fields>
        </Layer>
    </Layers>
</Protocol>

=== Riverscapes/QRiS/resources/beaver_census_protocol.xml
<Protocol machine_code="BEAVER_CENSUS" version="1.0" status="experimental" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="protocol.xsd">
    <Label>Beaver Census Protocol</Label>
    <Description>Beaver Census Layers</Description>
    <URL>https://lowtechpbr.restoration.usu.edu/</URL>
    <Citation> Wheaton J.M., Bennett S.N., Bouwes, N., Maestas J.D. and Shahverdian S.M. (Editors). 2019. Low-Tech Process-Based Restoration of Riverscapes: Design Manual. Version 1.0. Utah State University Restoration Consortium. Logan, UT. 286 pp. DOI: 10.13140/RG.2.2.19590.63049/2.</Citation>
    <Author>Jordan Gilbert</Author>
    <CreationDate>2024-09-01</CreationDate>
    <UpdatedDate>2024-09-01</UpdatedDate>
    <Metadata>
        <MetadataItem>
            <Name>My Meta</Name>
            <Value>Data</Value>
        </MetadataItem>
    </Metadata>
    <Layers>
        <Layer id="beaver_dam" version="1.0" geom_type="Point">
            <Label>Beaver Dam</Label>
            <Symbology>beaver_dam.qml</Symbology>
            <Description>Beaver Dam Layer</Description>
            <Hierarchy>
                <HierarchyItem>Observations</HierarchyItem>
                <HierarchyItem>Beaver Activity</HierarchyItem>
            </Hierarchy>
            <Fields>
                <Field id="dam_cer" version="1.0" type="list">
                    <Label>Dam CER</Label>
                    <LookupValues>
                        <LookupValue>high</LookupValue>
                        <LookupValue>medium</LookupValue>
                        <LookupValue>low</LookupValue>
                    </LookupValues>
                </Field>
                <Field id="dam_type" version="1.0" type="list">
                    <Label>Dam Type</Label>
                    <LookupValues>
                        <LookupValue>active_dam</LookupValue>
                        <LookupValue>inactive_dam</LookupValue>
                        <LookupValue>relic</LookupValue>
                    </LookupValues>
                </Field>
                <Field id="type_cer" version="1.0" type="list">
                    <Label>Type CER</Label>
                    <LookupValues>
                        <LookupValue>high</LookupValue>
                        <LookupValue>medium</LookupValue>
                        <LookupValue>low</LookupValue>
                    </LookupValues>
                </Field>
            </Fields>
        </Layer>
        <Layer id="beaver_sign" version="1.0" geom_type="Point">
            <Label>Beaver Sign</Label>
            <Symbology>beaver_sign.qml</Symbology>
            <Description>Beaver Sign Layer</Description>
            <Hierarchy>
                <HierarchyItem>Observations</HierarchyItem>
                <HierarchyItem>Beaver Activity</HierarchyItem>
            </Hierarchy>
            <Fields>
                <Field id="sign_type" version="1.0" type="list">
                    <Label>Type</Label>
                    <LookupValues>
                        <LookupValue>bank_den</LookupValue>
                        <LookupValue>bank_lodge</LookupValue>
                        <LookupValue>canal</LookupValue>
                        <LookupValue>chew_stick</LookupValue>
                        <LookupValue>clipped_vegetation</LookupValue>
                        <LookupValue>felled_tree</LookupValue>
                        <LookupValue>food_cache</LookupValue>
                        <LookupValue>harvested_branches</LookupValue>
                        <LookupValue>other</LookupValue>
                        <LookupValue>pond_excavation</LookupValue>
                        <LookupValue>pond_lodge</LookupValue>
                        <LookupValue>scat</LookupValue>
                        <LookupValue>scent_mound</LookupValue>
                        <LookupValue>set_of_tracks</LookupValue>
                        <LookupValue>skid_trail</LookupValue>
                        <LookupValue>slide</LookupValue>
                    </LookupValues>
                </Field>
            </Fields> 
        </Layer>
    </Layers>
</Protocol>
